# Generated by Django 4.0.3 on 2023-05-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='free', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='can_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='자유게시판', max_length=20, unique=True),
        ),
    ]
